### ISSUE TITLE
Support native database types

### ISSUE THREAD

**Issue by dzubchik** [darsyn/ip#36]
Hi! 
Do you plan to add support for native database types like INET in postgres? Here is [library](https://github.com/opensoft/doctrine-postgres-types/blob/master/src/Doctrine/DBAL/PostgresTypes/InetType.php) that already do this, but there are lack of value objects

**Comment by zanbaldwin** [comment]
Most likely no. Storing the value of the IP address differently on different platforms will cause more issues than it will solve.

If your application will exclusively use Postgres then by all means create a custom Doctrine type since that would most likely be the better option, but it's probably best that this library try to remain platform-agnostic.
