### ISSUE TITLE
Your data could not be encoded because it contains invalid UTF8 characters.

### ISSUE THREAD

**Issue by TheJenne18** [darsyn/ip#38]
Since I have implemented Darsyn, I can't output my object that contains the IP Address in json.

This is a dump of the result that should me encoded to json:
`array:128 [▼
  0 => IpAddress {#9856 ▼
    -id: null
    -ipAddress: IP {#9857 ▼
      -ip: b"\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00À¨\x01\x00"
      -version: null
    }
    -hostname: null
    -hostDescription: null
    -phone: null
    -mac: null
    -additionalInformation: null
    -createdAt: null
    -updateAt: null
    -subnet: Subnet {#8158 ▶}
    -provider: null
    -user: null
    -datacenter: null
  }`

But when I try to encoded it to json, I receive the error: Your data could not be encoded because it contains invalid UTF8 characters.

**Comment by zanbaldwin** [comment]
I'll take a look at implementing the [`JsonSerializable` interface](http://php.net/manual/en/class.jsonserializable.php) to output `\uXXXX` escaped characters (though can't guarantee it will work).

If you want to output the IP address then it's best to use either [`getShortAddress()`](https://github.com/darsyn/ip/blob/master/src/IP.php#L83-L90) or [`getLongAddress()`](https://github.com/darsyn/ip/blob/master/src/IP.php#L100-L108) to return an appropriate ASCII-safe representation rather than just dumping the object.
When the `IP` object is casted to a string (such as when you try to dump it) it returns the binary blob by default instead of the human-readable representation.

**Comment by zanbaldwin** [comment]
Doesn't look like implementing `JsonSerializable` is going to be feasible because `json_encode` is escaping the escape characters (but I'll keep trying).

It's probably best in the mean time to transform the IP objects into human-readable strings (`$ip->ipAddress = $ip->ipAddress->getLongAddress()`) before pumping it into a serializer.

**Comment by zanbaldwin** [comment]
You can see what I tried to do at https://github.com/darsyn/ip/commit/c18ab098ae1908189ea3dea920565d718acc1da6, but unfortunately that didn't work - I'll ask around and on Stack Overflow to see if anyone else has any ideas.

One possibility is `utf8_encode()` but don't have enough time now to test it out properly.

**Comment by TheJenne18** [comment]
Is there a possibility that every time I need to request the IP address, I automatically receive the getShortAddress?

**Comment by zanbaldwin** [comment]
Either call `getShortAddress()` directly, or you could extend the class with:

```php
<?php

class MyIP extends \Darsyn\IP\IP
{
    public function __toString()
    {
        return $this->getShortAddress();
    }
}
```
