### ISSUE TITLE
Importing data takes longer in version 4 than it did in version 3

### ISSUE THREAD

**Issue by TheJenne18** [darsyn/ip#43]
When we import the IP addresses from the old IP system, version 4 takes 3 times as long as with version 3 did.

**Comment by zanbaldwin** [comment]
Eeek, I'll take a look at this over the next day or so - is there anything in particular you're doing?
- How many IP object instances are you creating?
- How many operations on each IP object are you doing?
- Has everything else other than this library stayed the same?
- Does this include database operations?

If your use-case is bulk-importing, then you will see a tiny performance drop (but over several thousand iterations it will be noticeable). I'll take a look at running Blackfire on this to see if there are any performance improvements that can be made :)

**Comment by zanbaldwin** [comment]
Using the following script:

```php
$count = 100000;
if (class_exists('\Darsyn\IP\Version\Multi')) {
    $start = microtime(true);
    for ($i = 0; $i < $count; $i++) {
        try {
            $ip = new \Darsyn\IP\Version\Multi('::ffff:7f00:1');
            if ($ip->inRange($ip->getBroadcastIp(16), 17)) {
                // Not default embedding strategy just to instantiate an extra class
                $ip->isDerived();
                return $ip->getProtocolAppropriateAddress();
            }
        } catch (\Darsyn\IP\Exception\IpException $e) {
        }
    }
    $duration = microtime(true) - $start;
} else {
    $start = microtime(true);
    for ($i = 0; $i < $count; $i++) {
        try {
            $ip = new \Darsyn\IP\IP('::ffff:7f00:1');
            if ($ip->inRange($ip->getBroadcastIp(16), 17)) {
                // Not default embedding strategy just to instantiate an extra class
                $ip->isDerived();
                return $ip->getShortAddress();
            }
        } catch (\Darsyn\IP\InvalidIpAddressException $e) {
        }
    }
    $duration = microtime(true) - $start;
}

echo 'Count: ' . $count . PHP_EOL;
echo 'Total: ' . $duration . ' seconds' . PHP_EOL;
echo 'Each:  ' . (($duration / $count) * 1000) . ' milliseconds' . PHP_EOL;
```

For tag `4.0.0-beta1`:

```
Count: 100000
Total: 17.25884 seconds
Each:  0.17258 milliseconds
```

For tag `3.3.1`:

```
Count: 100000
Total: 2.93313 seconds
Each:  0.02933 milliseconds
```

That was a bigger difference than I thought it would be - will investigate over the next few days. Thanks for bringing this up!

**Comment by zanbaldwin** [comment]
Thank you for taking the time to review this library and provide feedback, it's much appreciated! I've just released [`4.0.0-beta2`](https://github.com/darsyn/ip/tree/4.0.0-beta2) which include improvements addressing the speed problems reported in this issue :slightly_smiling_face: 

I've updated the way that IP address parsing happens; it's now offloaded into a static factory method instead of the constructor which greatly decreases the amount of processing for hard-coded address values that are known to be valid.

It means calling `IP::factory()` instead of `new IP()` but the numbers are pretty good:

| Version | Instantiation | Iterations | Time (each) |
|-----------|-------------|----|---------|
| [`3.3.1`](https://github.com/darsyn/ip/tree/3.3.1) | `new IP($ip)` | 100,000 | 0.02984 milliseconds |
| [`4.0.0-beta1`](https://github.com/darsyn/ip/tree/4.0.0-beta1) | `new IP($ip)` | 100,000 | 0.17430 milliseconds |
| [`4.0.0-beat2`](https://github.com/darsyn/ip/tree/4.0.0-beta2) | `IP::factory($ip)` | 100,000 | 0.05485 milliseconds |

There may be a few more improvements to be made (the slowest operation now is generating a binary bitmask), but there wouldn't be any noticeable improvements without removing features (such as embedding strategies or the consistent formatter).

It's just less than twice the speed of `3.3.1` - would you mind seeing how well the speed improvements work for your real world use-case? :slightly_smiling_face:

**Comment by TheJenne18** [comment]
After updating the package and imporove my own importer, the speed is negligible.

Version | Instantiation | Iterations | Time (each) | Time (total)
-- | -- | -- | -- | --
4.0.0-beat2 | IP::factory($ip) | 25.799 | 99.62626 milliseconds | 2570.2580740452 seconds

**Comment by TheJenne18** [comment]
Is it also possible to leave the possibility to instantiate the object with the constructor?

**Comment by zanbaldwin** [comment]
Are you able to share the script you used to test `4.0.0-beta2` speeds? I should be able to better understand your use-case and run it through a Blackfire profile :)

**Comment by coudenysj** [comment]
@zanbaldwin I don't think the static call causes the speed improvements. You create a new object in the factory method, so now you have an extra funtion call (factory + new) instead of one construct (new).

**Comment by zanbaldwin** [comment]
The factory method is so that address validation logic can be moved out of the constructor, meaning that every call to the constructor internally does not need to validate an address that it knows to be valid (new objects are instantiated every time you call `getNetworkIp()`, `getBroadcastIp()` and `inRange()` - in the case of `Multi::inRange()` this instantiation can happen *up to 6 times* [if there's an exception attempting `IPv4::inRange()` so retries as IPv6] so with the factory method that stops the validation having to be performed 6 times when internally you already know the address you're trying to instantiate is valid because it was generated internally).

That's awesome, I look forward to the script - it would be brilliant to both test the exact same code that mimics your setup (obviously if your code isn't open-source there's only so much you can share) and compare results, hopefully finding areas to improve :slightly_smiling_face:

Unfortunately without knowing how you're using this library anything I do is just guesswork. I'm mostly looking for what methods are being called and how often.

---

There was a request to leave instantiating using the constructor, but that means that validation wouldn't get run at all (exceptions would be thrown whenever you try to perform any actions on the value-object) so I'm not going to put that in - but the constructor is just protected so you could extend the class to add another factory method that doesn't perform validation if you trust the input coming in (from a database perhaps).

**Comment by coudenysj** [comment]
Right, I'm sorry, I missed the internal instantiations.

So, I tried to create a phpbench "test suite" for the different scenario's (https://github.com/coudenysj/ip/commit/69b6ef4bc3bb7d2131f3a8dcbd73bf1667935378), but it really doesn't make much sense (yet), because I don't test different usages of the library, just the creation of objects.

I'll try to make it into something the library can use, for now the (useless) results are here:

### 3.3.1
```
git checkout 3.3.1

./vendor/bin/phpbench run tests/Performance/IpBench.php --report=default
PhpBench 0.15-dev (@git_version@). Running benchmarks.
Using configuration file: phpbench.json

\Darsyn\IP\Tests\Performance\IpBench

    benchCreateIpV4               I0 P0         [μ Mo]/r: 22.131 22.131 (μs)    [μSD μRSD]/r: 0.000μs 0.00%
    benchCreateIpV6               I0 P0         [μ Mo]/r: 20.901 20.901 (μs)    [μSD μRSD]/r: 0.000μs 0.00%

2 subjects, 2 iterations, 200,000 revs, 0 rejects, 0 failures, 0 warnings
(best [mean mode] worst) = 20.901 [21.516 21.516] 20.901 (μs)
⅀T: 43.032μs μSD/r 0.000μs μRSD/r: 0.000%
suite: 133edc8bb8b2f697c017d83356d38c50edf24f1c, date: 2018-04-24, stime: 14:10:31
+-----------+-----------------+--------+--------+--------+------+----------+----------+--------------+----------------+
| benchmark | subject         | groups | params | revs   | iter | mem_peak | time_rev | comp_z_value | comp_deviation |
+-----------+-----------------+--------+--------+--------+------+----------+----------+--------------+----------------+
| IpBench   | benchCreateIpV4 |        | []     | 100000 | 0    | 981,088b | 22.131μs | 0.00σ        | 0.00%          |
| IpBench   | benchCreateIpV6 |        | []     | 100000 | 0    | 981,088b | 20.901μs | 0.00σ        | 0.00%          |
+-----------+-----------------+--------+--------+--------+------+----------+----------+--------------+----------------+

```

### 4.0.0-alpha
```
git checkout 4.0.0-alpha

./vendor/bin/phpbench run tests/Performance/IpNewBench.php --report=default
PhpBench 0.15-dev (@git_version@). Running benchmarks.
Using configuration file: phpbench.json

\Darsyn\IP\Tests\Performance\IpNewBench

    benchCreateIpV4               I0 P0         [μ Mo]/r: 28.550 28.550 (μs)    [μSD μRSD]/r: 0.000μs 0.00%
    benchCreateIpV6               I0 P0         [μ Mo]/r: 45.570 45.570 (μs)    [μSD μRSD]/r: 0.000μs 0.00%
    benchCreateIpMulti            I0 P0         [μ Mo]/r: 74.672 74.672 (μs)    [μSD μRSD]/r: 0.000μs 0.00%

3 subjects, 3 iterations, 300,000 revs, 0 rejects, 0 failures, 0 warnings
(best [mean mode] worst) = 28.550 [49.597 49.597] 28.550 (μs)
⅀T: 148.791μs μSD/r 0.000μs μRSD/r: 0.000%
suite: 133edc892d72b3adb8cc140e483ffd823fea0cd8, date: 2018-04-24, stime: 14:16:18
+------------+--------------------+--------+--------+--------+------+------------+----------+--------------+----------------+
| benchmark  | subject            | groups | params | revs   | iter | mem_peak   | time_rev | comp_z_value | comp_deviation |
+------------+--------------------+--------+--------+--------+------+------------+----------+--------------+----------------+
| IpNewBench | benchCreateIpV4    |        | []     | 100000 | 0    | 1,004,456b | 28.550μs | 0.00σ        | 0.00%          |
| IpNewBench | benchCreateIpV6    |        | []     | 100000 | 0    | 1,005,056b | 45.570μs | 0.00σ        | 0.00%          |
| IpNewBench | benchCreateIpMulti |        | []     | 100000 | 0    | 1,062,536b | 74.672μs | 0.00σ        | 0.00%          |
+------------+--------------------+--------+--------+--------+------+------------+----------+--------------+----------------+
```

### 4.0.0-beta2
```
git checkout 4.0.0-beta2

./vendor/bin/phpbench run tests/Performance/IpFactoryBench.php --report=default
PhpBench 0.15-dev (@git_version@). Running benchmarks.
Using configuration file: phpbench.json

\Darsyn\IP\Tests\Performance\IpFactoryBench

    benchCreateIpV4               I0 P0         [μ Mo]/r: 20.942 20.942 (μs)    [μSD μRSD]/r: 0.000μs 0.00%
    benchCreateIpV6               I0 P0         [μ Mo]/r: 38.044 38.044 (μs)    [μSD μRSD]/r: 0.000μs 0.00%
    benchCreateIpMulti            I0 P0         [μ Mo]/r: 39.471 39.471 (μs)    [μSD μRSD]/r: 0.000μs 0.00%

3 subjects, 3 iterations, 300,000 revs, 0 rejects, 0 failures, 0 warnings
(best [mean mode] worst) = 20.942 [32.819 32.819] 20.942 (μs)
⅀T: 98.457μs μSD/r 0.000μs μRSD/r: 0.000%
suite: 133edc896adcd3a7eef6bfcdaaacd17e7da6e234, date: 2018-04-24, stime: 14:21:04
+----------------+--------------------+--------+--------+--------+------+------------+----------+--------------+----------------+
| benchmark      | subject            | groups | params | revs   | iter | mem_peak   | time_rev | comp_z_value | comp_deviation |
+----------------+--------------------+--------+--------+--------+------+------------+----------+--------------+----------------+
| IpFactoryBench | benchCreateIpV4    |        | []     | 100000 | 0    | 1,006,000b | 20.942μs | 0.00σ        | 0.00%          |
| IpFactoryBench | benchCreateIpV6    |        | []     | 100000 | 0    | 1,006,328b | 38.044μs | 0.00σ        | 0.00%          |
| IpFactoryBench | benchCreateIpMulti |        | []     | 100000 | 0    | 1,065,336b | 39.471μs | 0.00σ        | 0.00%          |
+----------------+--------------------+--------+--------+--------+------+------------+----------+--------------+----------------+
```
