### ISSUE TITLE
Default gateway

### ISSUE THREAD

**Issue by TheJenne18** [darsyn/ip#47]
Hello,

Is it possible to add the feature to receive a default gateway from a subnet?

Same as we can to with getNetworkIp and getBroadcastIp.

Basically it is the network address + 1.

**Comment by zanbaldwin** [comment]
Should be simple enough as I believe it's just a bitwise OR operation, I'll look into this!

**Comment by zanbaldwin** [comment]
So after a month of looking for a solution to this I cannot find any way to add two binary strings together!
Because IPv6 are 128-bit numbers, the only way I've found is `moontoast/math` and I don't particularly want to add dependencies to do one piece of processing. If more reasons come up to use it I might add it as a suggestion :+1: (unless you have any other suggestions for adding two 128-bit binary strings together)
